# Generated by Django 4.2.6 on 2025-05-05 06:44

import api.models
from decimal import Decimal
from django.db import migrations, models
import enumchoicefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.UUIDField(primary_key=True, serialize=False)),
                ('transaction_type', enumchoicefield.fields.EnumChoiceField(default=api.models.TransactionType(1), enum_class=api.models.TransactionType, max_length=15)),
                ('wallet_provider', enumchoicefield.fields.EnumChoiceField(blank=True, enum_class=api.models.WalletProvider, max_length=8, null=True)),
                ('bank_provider', enumchoicefield.fields.EnumChoiceField(blank=True, enum_class=api.models.BankProvider, max_length=11, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('agent_id', models.UUIDField()),
                ('customer_identifier', models.CharField(max_length=100)),
                ('status', enumchoicefield.fields.EnumChoiceField(default=api.models.TransactionStatus(1), enum_class=api.models.TransactionStatus, max_length=10)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('commission_status', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['agent_id'], name='api_transac_agent_i_e39f8b_idx'), models.Index(fields=['status'], name='api_transac_status_0f4e6a_idx'), models.Index(fields=['created_at'], name='api_transac_created_752f02_idx')],
            },
        ),
    ]
