# Generated by Django 4.2.6 on 2025-05-07 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='agent_id',
            field=models.CharField(max_length=50),
        ),
    ]
