# Generated by Django 4.2.20 on 2025-05-06 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='float_balance',
        ),
    ]
