# Generated by Django 4.2.9 on 2025-05-07 10:34

import api.models
from decimal import Decimal
from django.db import migrations, models
import enumchoicefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.CharField(max_length=100, unique=True)),
                ('wallet_load_rate', models.DecimalField(decimal_places=2, default=Decimal('1.50'), max_digits=5)),
                ('bank_deposit_rate', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5)),
                ('bank_withdrawal_rate', models.DecimalField(decimal_places=2, default=Decimal('1.25'), max_digits=5)),
                ('is_eligible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'commission_rates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommissionTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('agent_id', models.CharField(max_length=100)),
                ('transaction_type', enumchoicefield.fields.EnumChoiceField(enum_class=api.models.TransactionType, max_length=20)),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('commission_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', enumchoicefield.fields.EnumChoiceField(default='PENDING', enum_class=api.models.TransactionStatus, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'commission_transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
