# Generated by Django 4.2.9 on 2025-05-07 10:38

import api.models
from django.db import migrations
import enumchoicefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissiontransaction',
            name='status',
            field=enumchoicefield.fields.EnumChoiceField(default=api.models.TransactionStatus(1), enum_class=api.models.TransactionStatus, max_length=10),
        ),
    ]
